package com.multicommerce.model;
// Generated 24 mars 2025, 00:24:47 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Augmentationsalaire generated by hbm2java
 */
public class Augmentationsalaire implements java.io.Serializable {

	private int idaugmentation;
	private Integer idcontrat;
	private Integer idvariete;
	private Date date;
	private Boolean isvalide;
	private Byte montantprecedent;
	private Byte nouveaumontant;

	public Augmentationsalaire() {
	}

	public Augmentationsalaire(int idaugmentation) {
		this.idaugmentation = idaugmentation;
	}

	public Augmentationsalaire(int idaugmentation, Integer idcontrat, Integer idvariete, Date date, Boolean isvalide,
			Byte montantprecedent, Byte nouveaumontant) {
		this.idaugmentation = idaugmentation;
		this.idcontrat = idcontrat;
		this.idvariete = idvariete;
		this.date = date;
		this.isvalide = isvalide;
		this.montantprecedent = montantprecedent;
		this.nouveaumontant = nouveaumontant;
	}

	public int getIdaugmentation() {
		return this.idaugmentation;
	}

	public void setIdaugmentation(int idaugmentation) {
		this.idaugmentation = idaugmentation;
	}

	public Integer getIdcontrat() {
		return this.idcontrat;
	}

	public void setIdcontrat(Integer idcontrat) {
		this.idcontrat = idcontrat;
	}

	public Integer getIdvariete() {
		return this.idvariete;
	}

	public void setIdvariete(Integer idvariete) {
		this.idvariete = idvariete;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Boolean getIsvalide() {
		return this.isvalide;
	}

	public void setIsvalide(Boolean isvalide) {
		this.isvalide = isvalide;
	}

	public Byte getMontantprecedent() {
		return this.montantprecedent;
	}

	public void setMontantprecedent(Byte montantprecedent) {
		this.montantprecedent = montantprecedent;
	}

	public Byte getNouveaumontant() {
		return this.nouveaumontant;
	}

	public void setNouveaumontant(Byte nouveaumontant) {
		this.nouveaumontant = nouveaumontant;
	}

}
