package com.multicommerce.model;
// Generated 24 mars 2025, 00:24:47 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idclient;
	private Integer pointfidelite;
	private Date dateinscription;
	@SuppressWarnings("rawtypes")
	private Set preferences = new HashSet(0);

	public Client() {
	}

	public Client(int idclient) {
		this.idclient = idclient;
	}

	public Client(int idclient, Integer pointfidelite, Date dateinscription, @SuppressWarnings("rawtypes") Set preferences) {
		this.idclient = idclient;
		this.pointfidelite = pointfidelite;
		this.dateinscription = dateinscription;
		this.preferences = preferences;
	}

	public int getIdclient() {
		return this.idclient;
	}

	public void setIdclient(int idclient) {
		this.idclient = idclient;
	}

	public Integer getPointfidelite() {
		return this.pointfidelite;
	}

	public void setPointfidelite(Integer pointfidelite) {
		this.pointfidelite = pointfidelite;
	}

	public Date getDateinscription() {
		return this.dateinscription;
	}

	public void setDateinscription(Date dateinscription) {
		this.dateinscription = dateinscription;
	}

	@SuppressWarnings("rawtypes")
	public Set getPreferences() {
		return this.preferences;
	}

	public void setPreferences(Set preferences) {
		this.preferences = preferences;
	}

}
