package com.multicommerce.model;
// Generated 24 mars 2025, 00:24:47 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Collaborateur generated by hbm2java
 */
public class Collaborateur implements java.io.Serializable {

	private CollaborateurId id;
	private Date date;
	private Set contrats = new HashSet(0);
	private Set typecollaborateurs = new HashSet(0);

	public Collaborateur() {
	}

	public Collaborateur(CollaborateurId id) {
		this.id = id;
	}

	public Collaborateur(CollaborateurId id, Date date, Set contrats, Set typecollaborateurs) {
		this.id = id;
		this.date = date;
		this.contrats = contrats;
		this.typecollaborateurs = typecollaborateurs;
	}

	public CollaborateurId getId() {
		return this.id;
	}

	public void setId(CollaborateurId id) {
		this.id = id;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Set getContrats() {
		return this.contrats;
	}

	public void setContrats(Set contrats) {
		this.contrats = contrats;
	}

	public Set getTypecollaborateurs() {
		return this.typecollaborateurs;
	}

	public void setTypecollaborateurs(Set typecollaborateurs) {
		this.typecollaborateurs = typecollaborateurs;
	}

}
