package com.multicommerce.model;
// Generated 24 mars 2025, 00:24:47 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Compteutilisateur generated by hbm2java
 */
public class Compteutilisateur implements java.io.Serializable {

	private int idcompte;
	private int idutilisateur;
	private String login;
	private String motpasse;
	private String etat;
	private Timestamp datecreation;
	private String codesecret;
	private Set profiles = new HashSet(0);

	public Compteutilisateur() {
	}

	public Compteutilisateur(int idcompte, int idutilisateur) {
		this.idcompte = idcompte;
		this.idutilisateur = idutilisateur;
	}

	public Compteutilisateur(int idcompte, int idutilisateur, String login, String motpasse, String etat,
			Timestamp datecreation, String codesecret, Set profiles) {
		this.idcompte = idcompte;
		this.idutilisateur = idutilisateur;
		this.login = login;
		this.motpasse = motpasse;
		this.etat = etat;
		this.datecreation = datecreation;
		this.codesecret = codesecret;
		this.profiles = profiles;
	}

	public int getIdcompte() {
		return this.idcompte;
	}

	public void setIdcompte(int idcompte) {
		this.idcompte = idcompte;
	}

	public int getIdutilisateur() {
		return this.idutilisateur;
	}

	public void setIdutilisateur(int idutilisateur) {
		this.idutilisateur = idutilisateur;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getMotpasse() {
		return this.motpasse;
	}

	public void setMotpasse(String motpasse) {
		this.motpasse = motpasse;
	}

	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	public Timestamp getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Timestamp datecreation) {
		this.datecreation = datecreation;
	}

	public String getCodesecret() {
		return this.codesecret;
	}

	public void setCodesecret(String codesecret) {
		this.codesecret = codesecret;
	}

	public Set getProfiles() {
		return this.profiles;
	}

	public void setProfiles(Set profiles) {
		this.profiles = profiles;
	}

}
