package com.multicommerce.model;
// Generated 24 mars 2025, 00:24:47 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Conge generated by hbm2java
 */
public class Conge implements java.io.Serializable {

	private int idconge;
	private Integer idemploye;
	private Integer idtypeconge;
	private Date datedeb;
	private Date datefin;
	private Set motifs = new HashSet(0);

	public Conge() {
	}

	public Conge(int idconge) {
		this.idconge = idconge;
	}

	public Conge(int idconge, Integer idemploye, Integer idtypeconge, Date datedeb, Date datefin, Set motifs) {
		this.idconge = idconge;
		this.idemploye = idemploye;
		this.idtypeconge = idtypeconge;
		this.datedeb = datedeb;
		this.datefin = datefin;
		this.motifs = motifs;
	}

	public int getIdconge() {
		return this.idconge;
	}

	public void setIdconge(int idconge) {
		this.idconge = idconge;
	}

	public Integer getIdemploye() {
		return this.idemploye;
	}

	public void setIdemploye(Integer idemploye) {
		this.idemploye = idemploye;
	}

	public Integer getIdtypeconge() {
		return this.idtypeconge;
	}

	public void setIdtypeconge(Integer idtypeconge) {
		this.idtypeconge = idtypeconge;
	}

	public Date getDatedeb() {
		return this.datedeb;
	}

	public void setDatedeb(Date datedeb) {
		this.datedeb = datedeb;
	}

	public Date getDatefin() {
		return this.datefin;
	}

	public void setDatefin(Date datefin) {
		this.datefin = datefin;
	}

	public Set getMotifs() {
		return this.motifs;
	}

	public void setMotifs(Set motifs) {
		this.motifs = motifs;
	}

}
