package com.multicommerce.model;
// Generated 24 mars 2025, 00:24:47 by Hibernate Tools 6.5.1.Final

import java.io.Serializable;
import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contrat generated by hbm2java
 */
public class Contrat implements java.io.Serializable {

	private int idcontrat;
	private Collaborateur collaborateur;
	private Typecontrat typecontrat;
	private Date datedeb;
	private Date datefin;
	private Serializable avantages;
	private Boolean isvalid;
	private Serializable clauses;
	private Set salaires = new HashSet(0);
	private Set employes = new HashSet(0);

	public Contrat() {
	}

	public Contrat(int idcontrat) {
		this.idcontrat = idcontrat;
	}

	public Contrat(int idcontrat, Collaborateur collaborateur, Typecontrat typecontrat, Date datedeb, Date datefin,
			Serializable avantages, Boolean isvalid, Serializable clauses, Set salaires, Set employes) {
		this.idcontrat = idcontrat;
		this.collaborateur = collaborateur;
		this.typecontrat = typecontrat;
		this.datedeb = datedeb;
		this.datefin = datefin;
		this.avantages = avantages;
		this.isvalid = isvalid;
		this.clauses = clauses;
		this.salaires = salaires;
		this.employes = employes;
	}

	public int getIdcontrat() {
		return this.idcontrat;
	}

	public void setIdcontrat(int idcontrat) {
		this.idcontrat = idcontrat;
	}

	public Collaborateur getCollaborateur() {
		return this.collaborateur;
	}

	public void setCollaborateur(Collaborateur collaborateur) {
		this.collaborateur = collaborateur;
	}

	public Typecontrat getTypecontrat() {
		return this.typecontrat;
	}

	public void setTypecontrat(Typecontrat typecontrat) {
		this.typecontrat = typecontrat;
	}

	public Date getDatedeb() {
		return this.datedeb;
	}

	public void setDatedeb(Date datedeb) {
		this.datedeb = datedeb;
	}

	public Date getDatefin() {
		return this.datefin;
	}

	public void setDatefin(Date datefin) {
		this.datefin = datefin;
	}

	public Serializable getAvantages() {
		return this.avantages;
	}

	public void setAvantages(Serializable avantages) {
		this.avantages = avantages;
	}

	public Boolean getIsvalid() {
		return this.isvalid;
	}

	public void setIsvalid(Boolean isvalid) {
		this.isvalid = isvalid;
	}

	public Serializable getClauses() {
		return this.clauses;
	}

	public void setClauses(Serializable clauses) {
		this.clauses = clauses;
	}

	public Set getSalaires() {
		return this.salaires;
	}

	public void setSalaires(Set salaires) {
		this.salaires = salaires;
	}

	public Set getEmployes() {
		return this.employes;
	}

	public void setEmployes(Set employes) {
		this.employes = employes;
	}

}
