package com.multicommerce.model;
// Generated 24 mars 2025, 00:24:47 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employe generated by hbm2java
 */
public class Employe implements java.io.Serializable {

	private int idemploye;
	private Contrat contrat;
	private Patronboutique patronboutique;
	private Poste poste;
	private Integer poste_1;
	private Date dateembauche;
	private Integer contrat_1;
	private Integer salaire;
	private Integer statutemploye;
	private Set horairetravails = new HashSet(0);

	public Employe() {
	}

	public Employe(int idemploye) {
		this.idemploye = idemploye;
	}

	public Employe(int idemploye, Contrat contrat, Patronboutique patronboutique, Poste poste, Integer poste_1,
			Date dateembauche, Integer contrat_1, Integer salaire, Integer statutemploye, Set horairetravails) {
		this.idemploye = idemploye;
		this.contrat = contrat;
		this.patronboutique = patronboutique;
		this.poste = poste;
		this.poste_1 = poste_1;
		this.dateembauche = dateembauche;
		this.contrat_1 = contrat_1;
		this.salaire = salaire;
		this.statutemploye = statutemploye;
		this.horairetravails = horairetravails;
	}

	public int getIdemploye() {
		return this.idemploye;
	}

	public void setIdemploye(int idemploye) {
		this.idemploye = idemploye;
	}

	public Contrat getContrat() {
		return this.contrat;
	}

	public void setContrat(Contrat contrat) {
		this.contrat = contrat;
	}

	public Patronboutique getPatronboutique() {
		return this.patronboutique;
	}

	public void setPatronboutique(Patronboutique patronboutique) {
		this.patronboutique = patronboutique;
	}

	public Poste getPoste() {
		return this.poste;
	}

	public void setPoste(Poste poste) {
		this.poste = poste;
	}

	public Integer getPoste_1() {
		return this.poste_1;
	}

	public void setPoste_1(Integer poste_1) {
		this.poste_1 = poste_1;
	}

	public Date getDateembauche() {
		return this.dateembauche;
	}

	public void setDateembauche(Date dateembauche) {
		this.dateembauche = dateembauche;
	}

	public Integer getContrat_1() {
		return this.contrat_1;
	}

	public void setContrat_1(Integer contrat_1) {
		this.contrat_1 = contrat_1;
	}

	public Integer getSalaire() {
		return this.salaire;
	}

	public void setSalaire(Integer salaire) {
		this.salaire = salaire;
	}

	public Integer getStatutemploye() {
		return this.statutemploye;
	}

	public void setStatutemploye(Integer statutemploye) {
		this.statutemploye = statutemploye;
	}

	public Set getHorairetravails() {
		return this.horairetravails;
	}

	public void setHorairetravails(Set horairetravails) {
		this.horairetravails = horairetravails;
	}

}
