package com.multicommerce.model;
// Generated 24 mars 2025, 00:24:47 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Horairetravail generated by hbm2java
 */
public class Horairetravail implements java.io.Serializable {

	private int idht;
	private Timestamp datedebut;
	private Timestamp datefin;
	private String typejournee;
	private Integer valide;
	private Integer pause;
	private Set employes = new HashSet(0);

	public Horairetravail() {
	}

	public Horairetravail(int idht) {
		this.idht = idht;
	}

	public Horairetravail(int idht, Timestamp datedebut, Timestamp datefin, String typejournee, Integer valide,
			Integer pause, Set employes) {
		this.idht = idht;
		this.datedebut = datedebut;
		this.datefin = datefin;
		this.typejournee = typejournee;
		this.valide = valide;
		this.pause = pause;
		this.employes = employes;
	}

	public int getIdht() {
		return this.idht;
	}

	public void setIdht(int idht) {
		this.idht = idht;
	}

	public Timestamp getDatedebut() {
		return this.datedebut;
	}

	public void setDatedebut(Timestamp datedebut) {
		this.datedebut = datedebut;
	}

	public Timestamp getDatefin() {
		return this.datefin;
	}

	public void setDatefin(Timestamp datefin) {
		this.datefin = datefin;
	}

	public String getTypejournee() {
		return this.typejournee;
	}

	public void setTypejournee(String typejournee) {
		this.typejournee = typejournee;
	}

	public Integer getValide() {
		return this.valide;
	}

	public void setValide(Integer valide) {
		this.valide = valide;
	}

	public Integer getPause() {
		return this.pause;
	}

	public void setPause(Integer pause) {
		this.pause = pause;
	}

	public Set getEmployes() {
		return this.employes;
	}

	public void setEmployes(Set employes) {
		this.employes = employes;
	}

}
