package com.multicommerce.model;
// Generated 24 mars 2025, 00:24:47 by Hibernate Tools 6.5.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Motif generated by hbm2java
 */
public class Motif implements java.io.Serializable {

	private int idmotif;
	private Serializable motif;
	private Set conges = new HashSet(0);

	public Motif() {
	}

	public Motif(int idmotif) {
		this.idmotif = idmotif;
	}

	public Motif(int idmotif, Serializable motif, Set conges) {
		this.idmotif = idmotif;
		this.motif = motif;
		this.conges = conges;
	}

	public int getIdmotif() {
		return this.idmotif;
	}

	public void setIdmotif(int idmotif) {
		this.idmotif = idmotif;
	}

	public Serializable getMotif() {
		return this.motif;
	}

	public void setMotif(Serializable motif) {
		this.motif = motif;
	}

	public Set getConges() {
		return this.conges;
	}

	public void setConges(Set conges) {
		this.conges = conges;
	}

}
