package com.multicommerce.model;
// Generated 24 mars 2025, 00:24:47 by Hibernate Tools 6.5.1.Final

/**
 * Notifications generated by hbm2java
 */
public class Notifications implements java.io.Serializable {

	private int idnotifications;
	private Utilisateur utilisateur;
	private Boolean emailnotif;
	private Boolean alertesecurite;
	private Boolean alertetransaction;
	private Integer rappelpanier;

	public Notifications() {
	}

	public Notifications(int idnotifications) {
		this.idnotifications = idnotifications;
	}

	public Notifications(int idnotifications, Utilisateur utilisateur, Boolean emailnotif, Boolean alertesecurite,
			Boolean alertetransaction, Integer rappelpanier) {
		this.idnotifications = idnotifications;
		this.utilisateur = utilisateur;
		this.emailnotif = emailnotif;
		this.alertesecurite = alertesecurite;
		this.alertetransaction = alertetransaction;
		this.rappelpanier = rappelpanier;
	}

	public int getIdnotifications() {
		return this.idnotifications;
	}

	public void setIdnotifications(int idnotifications) {
		this.idnotifications = idnotifications;
	}

	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public Boolean getEmailnotif() {
		return this.emailnotif;
	}

	public void setEmailnotif(Boolean emailnotif) {
		this.emailnotif = emailnotif;
	}

	public Boolean getAlertesecurite() {
		return this.alertesecurite;
	}

	public void setAlertesecurite(Boolean alertesecurite) {
		this.alertesecurite = alertesecurite;
	}

	public Boolean getAlertetransaction() {
		return this.alertetransaction;
	}

	public void setAlertetransaction(Boolean alertetransaction) {
		this.alertetransaction = alertetransaction;
	}

	public Integer getRappelpanier() {
		return this.rappelpanier;
	}

	public void setRappelpanier(Integer rappelpanier) {
		this.rappelpanier = rappelpanier;
	}

}
