package com.multicommerce.model;
// Generated 24 mars 2025, 00:24:47 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Patronboutique generated by hbm2java
 */
public class Patronboutique implements java.io.Serializable {

	private int idpatron;
	private Set employes = new HashSet(0);

	public Patronboutique() {
	}

	public Patronboutique(int idpatron) {
		this.idpatron = idpatron;
	}

	public Patronboutique(int idpatron, Set employes) {
		this.idpatron = idpatron;
		this.employes = employes;
	}

	public int getIdpatron() {
		return this.idpatron;
	}

	public void setIdpatron(int idpatron) {
		this.idpatron = idpatron;
	}

	public Set getEmployes() {
		return this.employes;
	}

	public void setEmployes(Set employes) {
		this.employes = employes;
	}

}
