package com.multicommerce.model;
// Generated 24 mars 2025, 00:24:47 by Hibernate Tools 6.5.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Poste generated by hbm2java
 */
public class Poste implements java.io.Serializable {

	private int idposte;
	private String libelle;
	private String description;
	private Integer niveauresponsabilite;
	private Serializable competencesrequises;
	private Set employes = new HashSet(0);

	public Poste() {
	}

	public Poste(int idposte) {
		this.idposte = idposte;
	}

	public Poste(int idposte, String libelle, String description, Integer niveauresponsabilite,
			Serializable competencesrequises, Set employes) {
		this.idposte = idposte;
		this.libelle = libelle;
		this.description = description;
		this.niveauresponsabilite = niveauresponsabilite;
		this.competencesrequises = competencesrequises;
		this.employes = employes;
	}

	public int getIdposte() {
		return this.idposte;
	}

	public void setIdposte(int idposte) {
		this.idposte = idposte;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getNiveauresponsabilite() {
		return this.niveauresponsabilite;
	}

	public void setNiveauresponsabilite(Integer niveauresponsabilite) {
		this.niveauresponsabilite = niveauresponsabilite;
	}

	public Serializable getCompetencesrequises() {
		return this.competencesrequises;
	}

	public void setCompetencesrequises(Serializable competencesrequises) {
		this.competencesrequises = competencesrequises;
	}

	public Set getEmployes() {
		return this.employes;
	}

	public void setEmployes(Set employes) {
		this.employes = employes;
	}

}
