package com.multicommerce.model;
// Generated 24 mars 2025, 00:24:47 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Profile generated by hbm2java
 */
public class Profile implements java.io.Serializable {

	private int idprofile;
	private Compteutilisateur compteutilisateur;
	private String libelle;
	private Boolean etat;
	private String code;
	private Date datecreation;

	public Profile() {
	}

	public Profile(int idprofile, Compteutilisateur compteutilisateur) {
		this.idprofile = idprofile;
		this.compteutilisateur = compteutilisateur;
	}

	public Profile(int idprofile, Compteutilisateur compteutilisateur, String libelle, Boolean etat, String code,
			Date datecreation) {
		this.idprofile = idprofile;
		this.compteutilisateur = compteutilisateur;
		this.libelle = libelle;
		this.etat = etat;
		this.code = code;
		this.datecreation = datecreation;
	}

	public int getIdprofile() {
		return this.idprofile;
	}

	public void setIdprofile(int idprofile) {
		this.idprofile = idprofile;
	}

	public Compteutilisateur getCompteutilisateur() {
		return this.compteutilisateur;
	}

	public void setCompteutilisateur(Compteutilisateur compteutilisateur) {
		this.compteutilisateur = compteutilisateur;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Boolean getEtat() {
		return this.etat;
	}

	public void setEtat(Boolean etat) {
		this.etat = etat;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

}
