package com.multicommerce.model;
// Generated 24 mars 2025, 00:24:47 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private int idrole;
	private String nomrole;
	private String description;
	private Date datecreation;
	private Set permissions = new HashSet(0);
	private Set utilisateurs = new HashSet(0);

	public Role() {
	}

	public Role(int idrole) {
		this.idrole = idrole;
	}

	public Role(int idrole, String nomrole, String description, Date datecreation, Set permissions, Set utilisateurs) {
		this.idrole = idrole;
		this.nomrole = nomrole;
		this.description = description;
		this.datecreation = datecreation;
		this.permissions = permissions;
		this.utilisateurs = utilisateurs;
	}

	public int getIdrole() {
		return this.idrole;
	}

	public void setIdrole(int idrole) {
		this.idrole = idrole;
	}

	public String getNomrole() {
		return this.nomrole;
	}

	public void setNomrole(String nomrole) {
		this.nomrole = nomrole;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	public Set getPermissions() {
		return this.permissions;
	}

	public void setPermissions(Set permissions) {
		this.permissions = permissions;
	}

	public Set getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

}
