package com.multicommerce.model;
// Generated 24 mars 2025, 00:24:47 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Salaire generated by hbm2java
 */
public class Salaire implements java.io.Serializable {

	private int idsalaire;
	private Varietesalaire varietesalaire;
	private Byte montant;
	private Date datecreation;
	private Set contrats = new HashSet(0);

	public Salaire() {
	}

	public Salaire(int idsalaire) {
		this.idsalaire = idsalaire;
	}

	public Salaire(int idsalaire, Varietesalaire varietesalaire, Byte montant, Date datecreation, Set contrats) {
		this.idsalaire = idsalaire;
		this.varietesalaire = varietesalaire;
		this.montant = montant;
		this.datecreation = datecreation;
		this.contrats = contrats;
	}

	public int getIdsalaire() {
		return this.idsalaire;
	}

	public void setIdsalaire(int idsalaire) {
		this.idsalaire = idsalaire;
	}

	public Varietesalaire getVarietesalaire() {
		return this.varietesalaire;
	}

	public void setVarietesalaire(Varietesalaire varietesalaire) {
		this.varietesalaire = varietesalaire;
	}

	public Byte getMontant() {
		return this.montant;
	}

	public void setMontant(Byte montant) {
		this.montant = montant;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	public Set getContrats() {
		return this.contrats;
	}

	public void setContrats(Set contrats) {
		this.contrats = contrats;
	}

}
