package com.multicommerce.model;
// Generated 24 mars 2025, 00:24:47 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;

/**
 * Session generated by hbm2java
 */
public class Session implements java.io.Serializable {

	private int idhistorique;
	private Journalactivite journalactivite;
	private Utilisateur utilisateur;
	private Timestamp dateconnexion;
	private Timestamp datedeconnexion;
	private String adresseip;
	private String navigateur;
	private String systemeexploitation;
	private Integer statut;

	public Session() {
	}

	public Session(int idhistorique, Journalactivite journalactivite) {
		this.idhistorique = idhistorique;
		this.journalactivite = journalactivite;
	}

	public Session(int idhistorique, Journalactivite journalactivite, Utilisateur utilisateur, Timestamp dateconnexion,
			Timestamp datedeconnexion, String adresseip, String navigateur, String systemeexploitation,
			Integer statut) {
		this.idhistorique = idhistorique;
		this.journalactivite = journalactivite;
		this.utilisateur = utilisateur;
		this.dateconnexion = dateconnexion;
		this.datedeconnexion = datedeconnexion;
		this.adresseip = adresseip;
		this.navigateur = navigateur;
		this.systemeexploitation = systemeexploitation;
		this.statut = statut;
	}

	public int getIdhistorique() {
		return this.idhistorique;
	}

	public void setIdhistorique(int idhistorique) {
		this.idhistorique = idhistorique;
	}

	public Journalactivite getJournalactivite() {
		return this.journalactivite;
	}

	public void setJournalactivite(Journalactivite journalactivite) {
		this.journalactivite = journalactivite;
	}

	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public Timestamp getDateconnexion() {
		return this.dateconnexion;
	}

	public void setDateconnexion(Timestamp dateconnexion) {
		this.dateconnexion = dateconnexion;
	}

	public Timestamp getDatedeconnexion() {
		return this.datedeconnexion;
	}

	public void setDatedeconnexion(Timestamp datedeconnexion) {
		this.datedeconnexion = datedeconnexion;
	}

	public String getAdresseip() {
		return this.adresseip;
	}

	public void setAdresseip(String adresseip) {
		this.adresseip = adresseip;
	}

	public String getNavigateur() {
		return this.navigateur;
	}

	public void setNavigateur(String navigateur) {
		this.navigateur = navigateur;
	}

	public String getSystemeexploitation() {
		return this.systemeexploitation;
	}

	public void setSystemeexploitation(String systemeexploitation) {
		this.systemeexploitation = systemeexploitation;
	}

	public Integer getStatut() {
		return this.statut;
	}

	public void setStatut(Integer statut) {
		this.statut = statut;
	}

}
