package com.multicommerce.model;
// Generated 24 mars 2025, 00:24:47 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Typeutilisateur generated by hbm2java
 */
public class Typeutilisateur implements java.io.Serializable {

	private int idtypeuser;
	private String nomtype;
	private String description;
	private Integer niveauacces;
	private Set utilisateurs = new HashSet(0);

	public Typeutilisateur() {
	}

	public Typeutilisateur(int idtypeuser) {
		this.idtypeuser = idtypeuser;
	}

	public Typeutilisateur(int idtypeuser, String nomtype, String description, Integer niveauacces, Set utilisateurs) {
		this.idtypeuser = idtypeuser;
		this.nomtype = nomtype;
		this.description = description;
		this.niveauacces = niveauacces;
		this.utilisateurs = utilisateurs;
	}

	public int getIdtypeuser() {
		return this.idtypeuser;
	}

	public void setIdtypeuser(int idtypeuser) {
		this.idtypeuser = idtypeuser;
	}

	public String getNomtype() {
		return this.nomtype;
	}

	public void setNomtype(String nomtype) {
		this.nomtype = nomtype;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getNiveauacces() {
		return this.niveauacces;
	}

	public void setNiveauacces(Integer niveauacces) {
		this.niveauacces = niveauacces;
	}

	public Set getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

}
