package com.multicommerce.model;
// Generated 24 mars 2025, 00:24:47 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Typecontrat generated by hbm2java
 */
public class Typecontrat implements java.io.Serializable {

	private int idtypecontrat;
	private String nom;
	private String valeur;
	private String description;
	private Set contrats = new HashSet(0);

	public Typecontrat() {
	}

	public Typecontrat(int idtypecontrat) {
		this.idtypecontrat = idtypecontrat;
	}

	public Typecontrat(int idtypecontrat, String nom, String valeur, String description, Set contrats) {
		this.idtypecontrat = idtypecontrat;
		this.nom = nom;
		this.valeur = valeur;
		this.description = description;
		this.contrats = contrats;
	}

	public int getIdtypecontrat() {
		return this.idtypecontrat;
	}

	public void setIdtypecontrat(int idtypecontrat) {
		this.idtypecontrat = idtypecontrat;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getValeur() {
		return this.valeur;
	}

	public void setValeur(String valeur) {
		this.valeur = valeur;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getContrats() {
		return this.contrats;
	}

	public void setContrats(Set contrats) {
		this.contrats = contrats;
	}

}
