package com.multicommerce.model;
// Generated 24 mars 2025, 00:24:47 by Hibernate Tools 6.5.1.Final

/**
 * Typeconge generated by hbm2java
 */
public class Typeconge implements java.io.Serializable {

	private int idtypeconge;
	private String libelle;
	private String description;

	public Typeconge() {
	}

	public Typeconge(int idtypeconge) {
		this.idtypeconge = idtypeconge;
	}

	public Typeconge(int idtypeconge, String libelle, String description) {
		this.idtypeconge = idtypeconge;
		this.libelle = libelle;
		this.description = description;
	}

	public int getIdtypeconge() {
		return this.idtypeconge;
	}

	public void setIdtypeconge(int idtypeconge) {
		this.idtypeconge = idtypeconge;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
