package com.multicommerce.model;
// Generated 24 mars 2025, 00:24:47 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur implements java.io.Serializable {

	private int idutilisateur;
	private Typeutilisateur typeutilisateur;
	private Role role;
	private String nom;
	private String prenom;
	private String email;
	private String telephone;
	private String motpass;
	private Date datecreation;
	private Date derniereconnexion;
	private String adresse;
	private String codepostale;
	private Boolean actif;
	private String photo;
	private Set payses = new HashSet(0);
	private Set notificationses = new HashSet(0);
	private Set sessions = new HashSet(0);
	private Set villeses = new HashSet(0);

	public Utilisateur() {
	}

	public Utilisateur(int idutilisateur, Role role) {
		this.idutilisateur = idutilisateur;
		this.role = role;
	}

	public Utilisateur(int idutilisateur, Typeutilisateur typeutilisateur, Role role, String nom, String prenom,
			String email, String telephone, String motpass, Date datecreation, Date derniereconnexion, String adresse,
			String codepostale, Boolean actif, String photo, Set payses, Set notificationses, Set sessions,
			Set villeses) {
		this.idutilisateur = idutilisateur;
		this.typeutilisateur = typeutilisateur;
		this.role = role;
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
		this.telephone = telephone;
		this.motpass = motpass;
		this.datecreation = datecreation;
		this.derniereconnexion = derniereconnexion;
		this.adresse = adresse;
		this.codepostale = codepostale;
		this.actif = actif;
		this.photo = photo;
		this.payses = payses;
		this.notificationses = notificationses;
		this.sessions = sessions;
		this.villeses = villeses;
	}

	public int getIdutilisateur() {
		return this.idutilisateur;
	}

	public void setIdutilisateur(int idutilisateur) {
		this.idutilisateur = idutilisateur;
	}

	public Typeutilisateur getTypeutilisateur() {
		return this.typeutilisateur;
	}

	public void setTypeutilisateur(Typeutilisateur typeutilisateur) {
		this.typeutilisateur = typeutilisateur;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getMotpass() {
		return this.motpass;
	}

	public void setMotpass(String motpass) {
		this.motpass = motpass;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	public Date getDerniereconnexion() {
		return this.derniereconnexion;
	}

	public void setDerniereconnexion(Date derniereconnexion) {
		this.derniereconnexion = derniereconnexion;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public String getCodepostale() {
		return this.codepostale;
	}

	public void setCodepostale(String codepostale) {
		this.codepostale = codepostale;
	}

	public Boolean getActif() {
		return this.actif;
	}

	public void setActif(Boolean actif) {
		this.actif = actif;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public Set getPayses() {
		return this.payses;
	}

	public void setPayses(Set payses) {
		this.payses = payses;
	}

	public Set getNotificationses() {
		return this.notificationses;
	}

	public void setNotificationses(Set notificationses) {
		this.notificationses = notificationses;
	}

	public Set getSessions() {
		return this.sessions;
	}

	public void setSessions(Set sessions) {
		this.sessions = sessions;
	}

	public Set getVilleses() {
		return this.villeses;
	}

	public void setVilleses(Set villeses) {
		this.villeses = villeses;
	}

}
