package com.multicommerce.model;
// Generated 24 mars 2025, 00:24:47 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Varietesalaire generated by hbm2java
 */
public class Varietesalaire implements java.io.Serializable {

	private int idvariete;
	private String nom;
	private String valeur;
	private Set salaires = new HashSet(0);

	public Varietesalaire() {
	}

	public Varietesalaire(int idvariete) {
		this.idvariete = idvariete;
	}

	public Varietesalaire(int idvariete, String nom, String valeur, Set salaires) {
		this.idvariete = idvariete;
		this.nom = nom;
		this.valeur = valeur;
		this.salaires = salaires;
	}

	public int getIdvariete() {
		return this.idvariete;
	}

	public void setIdvariete(int idvariete) {
		this.idvariete = idvariete;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getValeur() {
		return this.valeur;
	}

	public void setValeur(String valeur) {
		this.valeur = valeur;
	}

	public Set getSalaires() {
		return this.salaires;
	}

	public void setSalaires(Set salaires) {
		this.salaires = salaires;
	}

}
